# Generated by Django 4.2.6 on 2023-10-18 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_cat_projects_created_at_projects_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projects',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projects',
            name='total_target',
            field=models.FloatField(default=None),
        ),
    ]
