# Generated by Django 4.2.6 on 2023-10-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_end_time_projects_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='total_target',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
