# Generated by Django 4.2.6 on 2023-10-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projects_total_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='total_target',
        ),
    ]
