# Generated by Django 4.2.6 on 2023-10-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projects_end_time_projects_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='total_target',
        ),
    ]
