# Generated by Django 4.2.6 on 2023-10-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_projects_total_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='total_target',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
