# Generated by Django 4.2.6 on 2023-10-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projects_total_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='total_target',
            field=models.IntegerField(),
        ),
    ]
