# Generated by Django 4.2.6 on 2023-10-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_projects_total_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='start_time',
        ),
    ]
