# Generated by Django 4.2.6 on 2023-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projects_created_at_projects_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FileField(max_length=200, null=True, upload_to='projects/images/'),
        ),
    ]
