# Generated by Django 4.2.6 on 2023-10-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_projects_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='projects/images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
