# Generated by Django 4.2.6 on 2023-10-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_review_item_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='projects',
            name='image2',
            field=models.ImageField(max_length=200, null=True, upload_to='projects/images/'),
        ),
    ]
