# Generated by Django 4.2.6 on 2023-10-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_rename_image_projects_image1_projects_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image3',
            field=models.ImageField(max_length=200, null=True, upload_to='projects/images/'),
        ),
    ]
