from django.urls import path
from custom_admin.views import admin_home, categories_list, create_donation, create_report, delete_donation, delete_report, donation, edit_donation, edit_report, projects_list, report, report_comments_list, reviews_list,review_create,review_edit,review_delete, tags_list, category_create, tag_create, category_edit, tag_edit, category_delete, tag_delete, user_create, user_delete, user_edit, user_profiles_list, users_list

urlpatterns = [
    path('admin_home/', admin_home, name='admin_home'),
    path('categories_list/', categories_list, name='categories_list'),
    path('category_create/', category_create, name='category_create'),
    path('category_edit/<int:id>/', category_edit, name='category_edit'),
    path('category_delete/<int:id>/', category_delete, name='category_delete'),
    path('tags_list/', tags_list, name='tags_list'),
    path('tag_create/', tag_create, name='tag_create'),
    path('tag_edit/<int:id>/', tag_edit, name='tag_edit'),
    path('tag_delete/<int:id>/', tag_delete, name='tag_delete'),
    path('donation/', donation, name='donation'),
    path('edit_donation/<int:pk>/', edit_donation, name='edit_donation'),
    path('delete_donation/<int:pk>/', delete_donation, name='delete_donation'),
    path('create_donation/', create_donation, name='create_donation'),
    path('report/', report, name='report'),
    path('edit_report/<int:pk>/', edit_report, name='edit_report'),
    path('delete_report/<int:pk>/', delete_report, name='delete_report'),
    path('create_report/', create_report, name='create_report'),
    path('users_list/', users_list, name='users_list'),
    path('user_create/', user_create, name='user_create'),
    path('user_edit/<int:id>/', user_edit, name='user_edit'),
    path('user_delete/<int:id>/', user_delete, name='user_delete'),
    path('user_profiles_list/', user_profiles_list, name='user_profiles_list'),
    path('projects_list/', projects_list, name='projects_list'),
    path('reviews_list/', reviews_list, name='reviews_list'),
    path('review_create/', review_create, name='review_create'),
    path('review_edit/<int:id>/', review_edit, name='review_edit'),
    path('review_delete/<int:id>/', review_delete, name='review_delete'),
    path('report_comments_list/', report_comments_list,
         name='report_comments_list'),
]
